# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 09:48
from __future__ import unicode_literals

import IncidentLocation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radius', models.FloatField(help_text='Radius of the incident', validators=[IncidentLocation.models.validate_positive_num])),
                ('coord_lat', models.FloatField(help_text='Latitude coordinate of the incident')),
                ('coord_long', models.FloatField(help_text='Longitude coordinate of the incident')),
            ],
        ),
    ]
