import os

TWIT_CONSUMER_KEY = os.environ.get('TWIT_CONSUMER_KEY')
TWIT_CONSUMER_SECRET = os.environ.get('TWIT_CONSUMER_SECRET')
TWIT_ACCESS_TOKEN = os.environ.get('TWIT_ACCESS_TOKEN')
TWIT_ACCESS_TOKEN_SECRET = os.environ.get('TWIT_ACCESS_TOKEN_SECRET')