import os

TWIT_CONSUMER_KEY = os.environ.get('TWIT_CONSUMER_KEY')
TWIT_CONSUMER_SECRET = os.environ.get('TWIT_CONSUMER_SECRET')
TWIT_ACCESS_TOKEN = os.environ.get('TWIT_ACCESS_TOKEN')
TWIT_ACCESS_TOKEN_SECRET = os.environ.get('TWIT_ACCESS_TOKEN_SECRET')

FB_PAGE_ID = os.environ.get('FB_PAGE_ID')
FB_PAGE_ACCESS_TOKEN = os.environ.get('FB_PAGE_ACCESS_TOKEN')

EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')