# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-24 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Incident', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incident',
            old_name='datetime',
            new_name='activation_time',
        ),
        migrations.AddField(
            model_name='incident',
            name='deactivation_time',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
