# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 05:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IncidentLocation', '0001_initial'),
        ('Incident', '0004_auto_20161018_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='IncidentLocation.IncidentLocation'),
        ),
    ]
