# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Incident', '0005_incident_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='activation_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='deactivation_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
