# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(help_text='Date and time of log')),
                ('description', models.TextField(help_text='Log description')),
            ],
        ),
    ]
