# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-08 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IncidentLog', '0003_auto_20161008_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentlog',
            name='description',
            field=models.TextField(default='Default log description', help_text='Log description'),
            preserve_default=False,
        ),
    ]
