# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentCallReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caller_name', models.TextField()),
                ('caller_nric', models.CharField(max_length=9)),
                ('contact_no', models.CharField(max_length=8)),
                ('description', models.TextField()),
                ('dateTime', models.DateField()),
                ('incident_id', models.IntegerField(help_text='Incident Id to link to')),
            ],
        ),
    ]
