# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-25 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentCallReport',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('caller_name', models.TextField()),
                ('caller_nric', models.CharField(max_length=9)),
                ('contact_no', models.CharField(max_length=8)),
                ('description', models.TextField()),
                ('Incident_type', models.CharField(max_length=1)),
                ('dateTime', models.DateField()),
            ],
        ),
    ]
