# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-25 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('agency_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('sms_contact_no', models.CharField(max_length=8)),
            ],
        ),
    ]
